run:
  deadline: 10m
  build-tags:
    - rpctest

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - exportloopref
    - gofmt
    - goimports
    - gosimple
    - govet
    - grouper
    - ineffassign
    - misspell
    - nilerr
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - tparallel
    - typecheck
    - unconvert
    - unused